analyzer:

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    unnecessary_lambdas: error
    unawaited_futures: error
    unrelated_type_equality_checks: error
    todo: ignore
    always_use_package_imports: error
    avoid_web_libraries_in_flutter: error
    list_remove_unrelated_type: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    avoid_returning_null_for_void: error
    prefer_void_to_null: error
    camel_case_extensions: error
    exhaustive_cases: error
    unnecessary_late: error
    unnecessary_new: error
    annotate_overrides: error
    avoid_empty_else: error
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    curly_braces_in_flow_control_structures: error
    unnecessary_nullable_for_final_variable_declarations: error
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    await_only_futures: error
    camel_case_types: error
    control_flow_in_finally: error #??
    empty_catches: error
    empty_statements: error
    iterable_contains_unrelated_type: error
    library_names: error
    library_prefixes: error
    recursive_getters: error
    non_constant_identifier_names: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_contains: error #??
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    use_rethrow_when_possible: error
    void_checks: error

  exclude:
    - 'lib/utils/pickers/date_picker_navigation_dailog.dart'
    - '**/*.g.dart'
    - 'lib/src/generated/*.dart'
    - '**/*.mocks.dart'
    - 'lib/l10n/generated/*.dart'

# example of all https://github.com/dart-lang/linter/blob/master/example/all.yaml
# explanation of all rules https://dart-lang.github.io/linter/lints/index.html
linter:
  rules:
    #nowe - dodane podczas mergowania modułów
    - always_use_package_imports
    - require_trailing_commas
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_void_to_null #recommended
    - avoid_bool_literals_in_conditional_expressions # https://dart-lang.github.io/linter/lints/avoid_bool_literals_in_conditional_expressions.html
    - avoid_field_initializers_in_const_classes
    - avoid_multiple_declarations_per_line
    - avoid_returning_null_for_void #recommended
    - avoid_redundant_argument_values
    - camel_case_extensions #recommended
    - curly_braces_in_flow_control_structures #recommended
    - exhaustive_cases #recommended
    - sized_box_shrink_expand
    - sort_child_properties_last
    - unnecessary_late #recommended
    #    - unnecessary_to_list_in_spreads
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - prefer_final_in_for_each
    #    - avoid_dynamic_calls #Odkomentować i dostosować kod podczas realziacji BL na usunięcie wszystkich dynamiców
    - unawaited_futures #do_przetestowania
    - unnecessary_lambdas
    - unnecessary_new #recommended
    - sized_box_for_whitespace
    #    - cancel_subscriptions #odkomentować i dostosować kod podczas realziacji BL na usunięcie zamknięcie wszyskich sinków
    - only_throw_errors
    #    - close_sinks #odkomentować i dostosować kod podczas realziacji BL na usunięcie zamknięcie wszyskich sinków
    - unnecessary_raw_strings
    - prefer_is_not_operator #recommended
    - unnecessary_const #recommended
    - unrelated_type_equality_checks #recommended
    - unnecessary_await_in_return
    - unnecessary_nullable_for_final_variable_declarations #recommended
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_specify_types
    - annotate_overrides #recommended
    - avoid_annotating_with_dynamic
    - avoid_empty_else #recommended
    - avoid_function_literals_in_foreach_calls #recommended #error?
    - avoid_init_to_null #recommended
    - avoid_null_checks_in_equality_operators #recommended
    - avoid_relative_lib_imports #recommended
    - avoid_renaming_method_parameters #recommended
    - avoid_return_types_on_setters #recommended
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - await_only_futures #recommended
    - camel_case_types #recommended
    - control_flow_in_finally #recommended
    - directives_ordering
    - empty_catches #recommended
    - empty_constructor_bodies #recommended
    - empty_statements #recommended
    - hash_and_equals #recommended
    - implementation_imports #recommended
    - iterable_contains_unrelated_type #recommended
    - library_names #recommended
    - library_prefixes #recommended
    - list_remove_unrelated_type #recommended
    - literal_only_boolean_expressions # https://github.com/flutter/flutter/issues/5791
    - no_adjacent_strings_in_list
    - no_duplicate_case_values #recommended
    - non_constant_identifier_names #recommended
    - package_api_docs
    - package_names #recommended
    - package_prefixed_library_names #recommended
    - prefer_adjacent_string_concatenation #recommended
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals #recommended
    - prefer_conditional_assignment #recommended
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains #recommended
    - prefer_final_fields #recommended
    - prefer_final_locals
    - prefer_foreach
    - prefer_initializing_formals #recommended
    - prefer_interpolation_to_compose_strings #recommended
    - prefer_is_empty #recommended
    - prefer_is_not_empty #recommended
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables #recommended
    - recursive_getters #recommended
    - slash_for_doc_comments #recommended
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals #recommended
    - unnecessary_brace_in_string_interps #recommended
    - unnecessary_getters_setters #recommended
    - unnecessary_null_aware_assignments #recommended
    - unnecessary_null_in_if_null_operators #recommended
    - unnecessary_overrides #recommended
    - unnecessary_parenthesis
    - unnecessary_statements # not yet tested
    - unnecessary_this
    - use_rethrow_when_possible #recommended
    - use_to_and_as_if_applicable
    - valid_regexps #recommended
    - void_checks #recommended