arb-dir: lib/l10n
template-arb-file: strings_pl.arb
output-localization-file: translations.dart
untranslated-messages-file: untranslated.json
synthetic-package: false
output-dir: lib/l10n/generated
output-class: Translations
header: // @dart = 2.12
