name: unclean_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: 8.1.2
  flutter_bloc: 8.1.3
  chopper: 6.1.3
  google_fonts: 5.0.0
  flutter_svg: 2.0.7
  get_it: 7.6.0
  analyzer: 5.13.0
  shared_preferences: 2.2.0
  equatable: 2.0.5
  json_annotation: 4.8.1
  json_serializable: 6.7.1
  provider: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  chopper_generator: 6.0.0
  injecteo_generator: 1.0.1
  freezed: 2.4.1
  freezed_annotation: 2.4.1

flutter:
  assets:
    - assets/icons/face_man.svg
  generate: true
  uses-material-design: true